package com.atguigu.tms.mock.bean;

/** Auto-decompiled from tms-mock JAR */
public class com.atguigu.tms.mock.bean.EmployeeInfo implements java.io.Serializable {
  private static final long serialVersionUID;
  private java.lang.Long id;
  private java.lang.String username;
  private java.lang.String password;
  private java.lang.String realName;
  private java.lang.String idCard;
  private java.util.Date birthday;
  private java.lang.String gender;
  private java.lang.String education;
  private java.util.Date graduationDate;
  private java.util.Date employmentDate;
  private java.lang.String phone;
  private java.lang.Long orgId;
  private java.lang.String positionType;
  private java.util.Date createTime;
  private java.util.Date updateTime;
  private java.lang.String isDeleted;
  public com.atguigu.tms.mock.bean.EmployeeInfo();
  public java.lang.Long getId();
  public java.lang.String getUsername();
  public java.lang.String getPassword();
  public java.lang.String getRealName();
  public java.lang.String getIdCard();
  public java.util.Date getBirthday();
  public java.lang.String getGender();
  public java.lang.String getEducation();
  public java.util.Date getGraduationDate();
  public java.util.Date getEmploymentDate();
  public java.lang.String getPhone();
  public java.lang.Long getOrgId();
  public java.lang.String getPositionType();
  public java.util.Date getCreateTime();
  public java.util.Date getUpdateTime();
  public java.lang.String getIsDeleted();
  public void setId(java.lang.Long);
  public void setUsername(java.lang.String);
  public void setPassword(java.lang.String);
  public void setRealName(java.lang.String);
  public void setIdCard(java.lang.String);
  public void setBirthday(java.util.Date);
  public void setGender(java.lang.String);
  public void setEducation(java.lang.String);
  public void setGraduationDate(java.util.Date);
  public void setEmploymentDate(java.util.Date);
  public void setPhone(java.lang.String);
  public void setOrgId(java.lang.Long);
  public void setPositionType(java.lang.String);
  public void setCreateTime(java.util.Date);
  public void setUpdateTime(java.util.Date);
  public void setIsDeleted(java.lang.String);
  public boolean equals(java.lang.Object);
  protected boolean canEqual(java.lang.Object);
  public int hashCode();
  public java.lang.String toString();
}
