package com.atguigu.tms.mock.bean;

/** Auto-decompiled from tms-mock JAR */
public class com.atguigu.tms.mock.bean.ExpressTaskCollect implements java.io.Serializable {
  private static final long serialVersionUID;
  private java.lang.Long id;
  private java.lang.Long orderId;
  private java.lang.String status;
  private java.lang.Long orgId;
  private java.lang.String orgName;
  private java.lang.Long courierEmpId;
  private java.lang.String courierName;
  private java.util.Date estimatedCollectedTime;
  private java.util.Date estimatedCommitTime;
  private java.util.Date actualCollectedTime;
  private java.util.Date actualCommitTime;
  private java.util.Date cancelTime;
  private java.lang.String remark;
  private java.util.Date createTime;
  private java.util.Date updateTime;
  private java.lang.String isDeleted;
  public com.atguigu.tms.mock.bean.ExpressTaskCollect();
  public java.lang.Long getId();
  public java.lang.Long getOrderId();
  public java.lang.String getStatus();
  public java.lang.Long getOrgId();
  public java.lang.String getOrgName();
  public java.lang.Long getCourierEmpId();
  public java.lang.String getCourierName();
  public java.util.Date getEstimatedCollectedTime();
  public java.util.Date getEstimatedCommitTime();
  public java.util.Date getActualCollectedTime();
  public java.util.Date getActualCommitTime();
  public java.util.Date getCancelTime();
  public java.lang.String getRemark();
  public java.util.Date getCreateTime();
  public java.util.Date getUpdateTime();
  public java.lang.String getIsDeleted();
  public void setId(java.lang.Long);
  public void setOrderId(java.lang.Long);
  public void setStatus(java.lang.String);
  public void setOrgId(java.lang.Long);
  public void setOrgName(java.lang.String);
  public void setCourierEmpId(java.lang.Long);
  public void setCourierName(java.lang.String);
  public void setEstimatedCollectedTime(java.util.Date);
  public void setEstimatedCommitTime(java.util.Date);
  public void setActualCollectedTime(java.util.Date);
  public void setActualCommitTime(java.util.Date);
  public void setCancelTime(java.util.Date);
  public void setRemark(java.lang.String);
  public void setCreateTime(java.util.Date);
  public void setUpdateTime(java.util.Date);
  public void setIsDeleted(java.lang.String);
  public boolean equals(java.lang.Object);
  protected boolean canEqual(java.lang.Object);
  public int hashCode();
  public java.lang.String toString();
}
