package com.atguigu.tms.mock.bean;

/** Auto-decompiled from tms-mock JAR */
public class com.atguigu.tms.mock.bean.LineBaseInfo implements java.io.Serializable {
  private static final long serialVersionUID;
  private java.lang.Long id;
  private java.lang.String name;
  private java.lang.String lineNo;
  private java.lang.Integer lineLevel;
  private java.lang.Long orgId;
  private java.lang.String transportLineTypeId;
  private java.lang.Long startOrgId;
  private java.lang.String startOrgName;
  private java.lang.Long endOrgId;
  private java.lang.String endOrgName;
  private java.lang.Long pairLineId;
  private java.math.BigDecimal distance;
  private java.math.BigDecimal cost;
  private java.lang.Integer estimatedTime;
  private java.lang.String status;
  private java.util.Date createTime;
  private java.util.Date updateTime;
  private java.lang.String isDeleted;
  public com.atguigu.tms.mock.bean.LineBaseInfo();
  public java.lang.Long getId();
  public java.lang.String getName();
  public java.lang.String getLineNo();
  public java.lang.Integer getLineLevel();
  public java.lang.Long getOrgId();
  public java.lang.String getTransportLineTypeId();
  public java.lang.Long getStartOrgId();
  public java.lang.String getStartOrgName();
  public java.lang.Long getEndOrgId();
  public java.lang.String getEndOrgName();
  public java.lang.Long getPairLineId();
  public java.math.BigDecimal getDistance();
  public java.math.BigDecimal getCost();
  public java.lang.Integer getEstimatedTime();
  public java.lang.String getStatus();
  public java.util.Date getCreateTime();
  public java.util.Date getUpdateTime();
  public java.lang.String getIsDeleted();
  public void setId(java.lang.Long);
  public void setName(java.lang.String);
  public void setLineNo(java.lang.String);
  public void setLineLevel(java.lang.Integer);
  public void setOrgId(java.lang.Long);
  public void setTransportLineTypeId(java.lang.String);
  public void setStartOrgId(java.lang.Long);
  public void setStartOrgName(java.lang.String);
  public void setEndOrgId(java.lang.Long);
  public void setEndOrgName(java.lang.String);
  public void setPairLineId(java.lang.Long);
  public void setDistance(java.math.BigDecimal);
  public void setCost(java.math.BigDecimal);
  public void setEstimatedTime(java.lang.Integer);
  public void setStatus(java.lang.String);
  public void setCreateTime(java.util.Date);
  public void setUpdateTime(java.util.Date);
  public void setIsDeleted(java.lang.String);
  public boolean equals(java.lang.Object);
  protected boolean canEqual(java.lang.Object);
  public int hashCode();
  public java.lang.String toString();
}
