package com.atguigu.tms.mock.bean;

/** Auto-decompiled from tms-mock JAR */
public class com.atguigu.tms.mock.bean.TransportTask implements java.io.Serializable {
  private static final long serialVersionUID;
  private java.lang.Long id;
  private java.lang.Long shiftId;
  private java.lang.Long lineId;
  private java.lang.Long startOrgId;
  private java.lang.String startOrgName;
  private java.lang.Long endOrgId;
  private java.lang.String endOrgName;
  private java.lang.String status;
  private java.lang.Integer orderNum;
  private java.lang.Long driver1EmpId;
  private java.lang.String driver1Name;
  private java.lang.Long driver2EmpId;
  private java.lang.String driver2Name;
  private java.lang.Long truckId;
  private java.lang.String truckNo;
  private java.util.Date actualStartTime;
  private java.util.Date actualEndTime;
  private java.lang.Long actualDistance;
  private java.util.Date createTime;
  private java.util.Date updateTime;
  private java.lang.String isDeleted;
  java.util.List<com.atguigu.tms.mock.bean.TransportTaskDetail> transportTaskDetailList;
  public com.atguigu.tms.mock.bean.TransportTask();
  public java.lang.Long getId();
  public java.lang.Long getShiftId();
  public java.lang.Long getLineId();
  public java.lang.Long getStartOrgId();
  public java.lang.String getStartOrgName();
  public java.lang.Long getEndOrgId();
  public java.lang.String getEndOrgName();
  public java.lang.String getStatus();
  public java.lang.Integer getOrderNum();
  public java.lang.Long getDriver1EmpId();
  public java.lang.String getDriver1Name();
  public java.lang.Long getDriver2EmpId();
  public java.lang.String getDriver2Name();
  public java.lang.Long getTruckId();
  public java.lang.String getTruckNo();
  public java.util.Date getActualStartTime();
  public java.util.Date getActualEndTime();
  public java.lang.Long getActualDistance();
  public java.util.Date getCreateTime();
  public java.util.Date getUpdateTime();
  public java.lang.String getIsDeleted();
  public java.util.List<com.atguigu.tms.mock.bean.TransportTaskDetail> getTransportTaskDetailList();
  public void setId(java.lang.Long);
  public void setShiftId(java.lang.Long);
  public void setLineId(java.lang.Long);
  public void setStartOrgId(java.lang.Long);
  public void setStartOrgName(java.lang.String);
  public void setEndOrgId(java.lang.Long);
  public void setEndOrgName(java.lang.String);
  public void setStatus(java.lang.String);
  public void setOrderNum(java.lang.Integer);
  public void setDriver1EmpId(java.lang.Long);
  public void setDriver1Name(java.lang.String);
  public void setDriver2EmpId(java.lang.Long);
  public void setDriver2Name(java.lang.String);
  public void setTruckId(java.lang.Long);
  public void setTruckNo(java.lang.String);
  public void setActualStartTime(java.util.Date);
  public void setActualEndTime(java.util.Date);
  public void setActualDistance(java.lang.Long);
  public void setCreateTime(java.util.Date);
  public void setUpdateTime(java.util.Date);
  public void setIsDeleted(java.lang.String);
  public void setTransportTaskDetailList(java.util.List<com.atguigu.tms.mock.bean.TransportTaskDetail>);
  public boolean equals(java.lang.Object);
  protected boolean canEqual(java.lang.Object);
  public int hashCode();
  public java.lang.String toString();
}
