package com.atguigu.tms.mock.bean;

/** Auto-decompiled from tms-mock JAR */
public class com.atguigu.tms.mock.bean.TruckModel implements java.io.Serializable {
  private static final long serialVersionUID;
  private java.lang.Long id;
  private java.lang.String modelName;
  private java.lang.String modelType;
  private java.lang.String modelNo;
  private java.lang.String brand;
  private java.math.BigDecimal truckWeight;
  private java.math.BigDecimal loadWeight;
  private java.math.BigDecimal totalWeight;
  private java.lang.String eev;
  private java.math.BigDecimal boxcarLen;
  private java.math.BigDecimal boxcarWd;
  private java.math.BigDecimal boxcarHg;
  private java.lang.Long maxSpeed;
  private java.lang.Long oilVol;
  private java.util.Date createTime;
  private java.util.Date updateTime;
  private java.lang.String isDeleted;
  public com.atguigu.tms.mock.bean.TruckModel();
  public java.lang.Long getId();
  public void setId(java.lang.Long);
  public java.lang.String getModelName();
  public void setModelName(java.lang.String);
  public java.lang.String getModelType();
  public void setModelType(java.lang.String);
  public java.lang.String getModelNo();
  public void setModelNo(java.lang.String);
  public java.lang.String getBrand();
  public void setBrand(java.lang.String);
  public java.math.BigDecimal getTruckWeight();
  public void setTruckWeight(java.math.BigDecimal);
  public java.math.BigDecimal getLoadWeight();
  public void setLoadWeight(java.math.BigDecimal);
  public java.math.BigDecimal getTotalWeight();
  public void setTotalWeight(java.math.BigDecimal);
  public java.lang.String getEev();
  public void setEev(java.lang.String);
  public java.math.BigDecimal getBoxcarLen();
  public void setBoxcarLen(java.math.BigDecimal);
  public java.math.BigDecimal getBoxcarWd();
  public void setBoxcarWd(java.math.BigDecimal);
  public java.math.BigDecimal getBoxcarHg();
  public void setBoxcarHg(java.math.BigDecimal);
  public java.lang.Long getMaxSpeed();
  public void setMaxSpeed(java.lang.Long);
  public java.lang.Long getOilVol();
  public void setOilVol(java.lang.Long);
  public java.util.Date getCreateTime();
  public void setCreateTime(java.util.Date);
  public java.util.Date getUpdateTime();
  public void setUpdateTime(java.util.Date);
  public java.lang.String getIsDeleted();
  public void setIsDeleted(java.lang.String);
  public java.lang.String toString();
}
